FINTPHOME=/home/fintp/fintp
FINTPLIB=$FINTPHOME/lib
FINTPCOREPATH=$FINTPHOME/core
FINTPLOGDIR=$FINTPHOME/logs
FINTPCONNECTORSPATH=$FINTPHOME/connectors
FINTPCORESTART="EventsWatcher RoutingEngine"
FINTPCORESTOP="EventsWatcher RoutingEngine"
FINTPCONNECTORSSTART="DBConnector FTPBOSEPConnector FTPACHSTPConnector"
FINTPCONNECTORSSTOP="DBConnector FTPBOSEPConnector FTPACHSTPConnector"


set -a FINTPSERVICESCORE EventsWatcher RoutingEngine
set -a FINTPSERVICESCOREID EW RE 
set -a FINTPSERVICESCONN DBConnector FTPBOSEPConnector FTPACHSTPConnector
set -a FINTPSERVICESCONNID DB BOSEP ACHSTP

FINTPSTOPTIMEOUT=300
LD_LIBRARY_PATH=/opt/mqm/lib64:/usr/local:/usr/lib/oracle/11.2/client64/lib:/home/fintp/fintp/lib:/home/oracle/app/oracle/product/11.2.0/client_1:$FINTPLIB

PATH=$PATH:$FINTPHOME:$FINTPCONNECTORSPATH:$FINTPCOREPATH
export FINTPSERVICESCORE FINTPSERVICESCOREID FINTPCORESTART FINTPCORESTOP FINTPSERVICESCONN FINTPSERVICESCONNID FINTPSTOPTIMEOUT FINTPCONNECTORSSTART FINTPCONNECTORSSTOP FINTPHOME FINTPLIB FINTPLOGDIR FINTPCOREPATH FINTPCONNECTORSPATH LIBPPATH PATH
